#!/bin/bash


echo "You can input path when call script as argument";
if [[ -z $1 ]]; then
            echo 'Path of git folder: Ctr+C to quit';
        while : ; do
                read path;
            if [[ -d ${path} ]]; then
                echo 'Path ok';
                cd ${path};
                break;
            else
                echo ${path} 'is not a directory';
            fi;
            done;
  else
        path=$1;
        cd ${path};
        echo ${path}' is ok';
fi
echo '======================Input list git to clone ====================';
echo 'Input URL of git: Example: git@git.solazu.net:wordpress/  or https://git.solazu.net/wordpress/'
read url_git;
echo 'Input name of git repository : Example: educef'
declare -a arr;
while : ; do
    read a;
    echo "Press :q to submit";
    if [[ ${a} = ":q" ]]; then
        break;
    fi
    arr=( "${arr[@]}" "$a" );
done
        echo 'If something wrong press ctr + c. Press any key to submit';
        echo ${arr[@]};
        read enter;

for git in ${arr[@]};do
    if [[ -d ${path}${git} ]]; then
        echo 'Already have'${git};
        else
        git clone ${url_git}${git}.git
    fi
done

#for (( i = 0 ; i<1 ; i++ )); do
#    echo '';
#done