#!/bin/bash




declare -a arr;
arr=(
'smb://192.168.3.253/solazu_drive/02_Themeforest/Transera/04_Submission/version3.0/' 
'smb://192.168.3.253/solazu_drive/02_Themeforest/Solabiz/04_Submission/WP/version1.8/' 
'smb://192.168.3.253/solazu_drive/02_Themeforest/SEOGrow/04_Submission/WP/version3.7/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/AppExpo/04_Submission/WP/version2.9/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Architect/03_Submission/WP/version1.4/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Flexi/04_Submission/WP/version3.0/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Hearty/04_Submission/WP/version3.8/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Grassy/04_Submission/WP/version1.5/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Jogy/04_Submission/WP/version1.6/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Lawplus/04_Submission/WP/version2.8/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/MagiClean/04_Submission/WP/version1.5/'
'smb://192.168.3.253/solazu_drive/02_Themeforest/Minimalist_Portfolio/03_Submission/version1.5/'
)

for i in ${arr[@]}; do
	
	a=	echo $i | sed -r 's#smb://#\\#g'

	

done

#echo ${arr[@]};
